name: Bump version

on:
  workflow_dispatch:

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: "${{ secrets.COMMITIZEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.COMMITIZEN }}
          changelog_increment_filename: body.md

  push-stable-and-release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    environment: pypi
    runs-on: ubuntu-latest
    name: "Push stable, release, and publish to pypi"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: "${{ secrets.COMMITIZEN }}"
      - name: Merge main -> stable
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: stable
          github_token: ${{ secrets.COMMITIZEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITIZEN }}
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.46.0
          cache: true
          environments: >-
            py310
            py311
            py312
      - name: Publish
        run: |
          pixi run -e py310 publish
          pixi run -e py311 publish
          pixi run -e py312 publish
