name: Publish

on:
  push:
    branches:
      - stable

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Publish across all Python versions"
    strategy:
      matrix:
        environment: [py310, py311, py312]
    steps:
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.46.0
          cache: true
          environments: ${{ matrix.environment }}
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.COMMITIZEN }}"
      - name: Test
        run: pixi run -e ${{ matrix.environment }} publish